### ISSUE TITLE
Check specification of time-stratified dataset

### ISSUE THREAD

**Issue by eparker12** [opensafely/ckd-coverage-ve#6]
https://github.com/opensafely/ckd-coverage-ve/blob/1dce1eee9243882ad3916e8350fc11d884c4ba79/analysis/VE/cox_preflight_VE.R#L281

A potential issue may have arisen in my original coding of the tmerge() function, where I used ` ind_outcome = event(tte_outcome)
  )` rather than  `ind_outcome = event(tte_outcome, ind_outcome)`. This meant that all individuals were assigned ind_outcome = TRUE in the final follow-up window, independent of whether this finished in a censoring event or outcome event.

My impression is that...
(i) if censor date is before outcome date, `ind_outcome` should be FALSE for all follow-up periods
(ii) if outcome date is before censor date, `ind_outcome` should become TRUE in the follow-up period in which the event happens
... and that the above modification addresses this issue. I would be grateful if you can double-check the specification of the tmerge() data.

**Comment by elsie-h** [comment]
Well spotted! I just checked and I agree that your fix is working.

I wonder if it would be better to rename `tte_outcome` to `tte_stop` to make it clear that it's time until censor or outcome, not just time until outcome?
